#!/usr/bin/env python

from sys import modules
from importlib import import_module
from os import path, getcwd, makedirs
from argparse import ArgumentParser
from configparser import ConfigParser


def get_config():
	# parse arguments
	parser = ArgumentParser()
	parser.add_argument('--workdir', nargs='?', default=getcwd())
	parser.add_argument('--config_file', nargs='?', default='config.ini')
	args = parser.parse_args()

	# assert path exists
	workdir = args.workdir
	config_file = path.join(workdir, args.config_file)
	assert path.exists(workdir)
	assert path.exists(config_file)

	# parse config.ini
	config = ConfigParser()
	config.read(config_file)

	# ensure output directory exists
	outdir = path.join(workdir, config['path']['output'])
	if not path.exists(outdir):
		makedirs(outdir)

	return config, workdir

		
def setup(config, workdir):
	# wrap path
	path_dict = dict()
	for dir in config['path']:
		if config['path'][dir] != 'no':
			path_dict[dir] = path.join(workdir, config['path'][dir])

	# import workflow
	mode = config['workflow']['mode']
	imported = getattr(import_module('seispie.workflow.' + mode), mode);
	imported.call = import_module('seispie.workflow.system.' + config['workflow']['system']).call

	# setup workflow
	workflow = imported()
	workflow.config = config['workflow']
	workflow.path = path_dict
	workflow.setup()

	# import and setup components
	for section in workflow.modules:
		# import component
		method = config[section]['method']
		imported = getattr(import_module('seispie.' + section + '.' + method), method)

		# setup component
		module = imported()
		module.config = config[section]
		module.path = path_dict
		module.setup()

		setattr(workflow, section, module)

	# start workflow
	workflow.run()


if __name__ == '__main__':
	setup(*get_config())
