#!/usr/bin/env python

from sys import modules
from importlib import import_module
from seispie.tools.config import get_config

def import_object(section, name):
	module = import_module('seispie.' + section + '.' + name);
	return getattr(module, name)()

		
def setup(config):
	# create workflow
	workflow = import_object('workflow', config['workflow']['mode'])
	workflow.setup(config['workflow'])

	# load components
	for section in workflow.modules:
		module = import_object(section, config[section]['method'])
		module.setup(config[section])
		setattr(workflow, section, module)

	# start workflow
	workflow.run()


if __name__ == '__main__':
	setup(get_config())
