#!/usr/bin/env python

from sys import modules
from importlib import import_module
from os import path, getcwd, makedirs
from argparse import ArgumentParser
from configparser import ConfigParser


def get_config():
	# parse arguments
	parser = ArgumentParser()
	parser.add_argument('--workdir', nargs='?', default=getcwd())
	parser.add_argument('--config_file', nargs='?', default='config.ini')
	args = parser.parse_args()

	# assert path exists
	workdir = args.workdir
	config_file = path.join(workdir, args.config_file)
	assert path.exists(workdir)
	assert path.exists(config_file)

	# parse config.ini
	config = ConfigParser()
	config.read(config_file)

	# ensure output directory exists
	outdir = path.join(workdir, config['path']['output'])
	if not path.exists(outdir):
		makedirs(outdir)

	return config, workdir

		
def setup(config, workdir):
	# system setup
	mode = config['workflow']['mode']
	Workflow = getattr(import_module('seispie.workflow.' + mode), mode);
	system = import_module('seispie.workflow.system.' + config['workflow']['system'])
	for method in ['call']:
		setattr(Workflow, method, getattr(system, method))

	# create workflow
	workflow = Workflow()
	workflow.setup(config['workflow'])

	# set path
	workflow.path = dict()
	for dir in config['path']:
		if config['path'][dir] != 'no':
			workflow.path[dir] = path.join(workdir, config['path'][dir])

	# load components
	for section in workflow.modules:
		method = config[section]['method']
		module = getattr(import_module('seispie.' + section + '.' + method), method)()
		module.setup(config[section])
		setattr(workflow, section, module)

	# start workflow
	workflow.run()


if __name__ == '__main__':
	setup(*get_config())
