#!/usr/bin/env python

import sys
from subprocess import call

if __name__ == '__main__':

	dir_path = 

	cmd = 'srun python ' + sys.argv[1] + '/srun'

	for i in range(2, len(sys.argv)):
		cmd += ' ' + sys.argv[i]

	# call(cmd, shell=True)
	print(cmd)

