#!/usr/bin/env python

import sys
from subprocess import call

if __name__ == '__main__':

	cmd = 'srun python ' + sys.argv[1] + '/sprun'

	for i in range(2, len(sys.argv)):
		cmd += ' ' + sys.argv[i]

	call(cmd, shell=True)
