#!/usr/bin/env python

from seispie.tools.config import get_config
from subprocess import call
import os, sys

if __name__ == '__main__':
	config = get_config()
	slurm = config['slurm']
	path = config['directory']
	output_dir = path['workdir'] + '/' + path['output']

	cmd = 'sbatch '

	if 'args' in slurm:
		cmd += '%s ' % slurm['args']

	if 'name' in slurm:
		cmd += '--job-name=%s ' % slurm['name']

	cmd += '--output=%s ' % (output_dir+'/'+'output.log')
	cmd += '--ntasks-per-node=%s ' % slurm['tasks_per_node']
	cmd += '--nodes=%s ' % slurm['nodes']
	cmd += '--time=%s ' % slurm['time']
	cmd += 'spsrun ' + os.path.dirname(os.path.realpath(__file__))

	for i in range(1, len(sys.argv)):
		cmd += ' %s' % sys.argv[i]

	call(cmd, shell=True)
